### ISSUE TITLE
LD for multiple chromosomes

### ISSUE THREAD

**Issue by KamilSJaron** [KamilSJaron/Conjunction#7]
This [setting](https://github.com/KamilSJaron/Conjunction/files/417277/err_C.txt) for testing decay of LD for indipendent loci (i.e. on different chromosomes) is reporting -inf. Intermediate computations look correct (var(HI) and var(p))

Apparently linked loci are producing values of LD in meaningful range (0.0.25).

**Comment by StuartJEBaird** [comment]
If I understand: this is a neat way of showing the fix for the earlier LD
problem?

S
